<html>
<head>
</head>

<body>

<p style="font-family:'Calibri',sans-serif">Hello *|RECIPIENT|*,</p><br>
<p style="font-family:'Calibri',sans-serif">*|SENDER|* sent you an encrypted email using <a href='https://scryptmail.com'>SCRYPTmail</a>.<br>
You can read this email by clicking the following link: <a href='*|LINK_TO_MESSAGE|*'>Show email</a></p><br>
<p style="font-family:'Calibri',sans-serif">*|LINK_TO_MESSAGE|*</p><br><br>

<p style="font-family:'Calibri',sans-serif">The original email will be available for the next 14 days, and after this time has elapsed, it will be deleted. You can also delete it by following link and selecting delete.</p><br><br>

<p style="font-family:'Calibri',sans-serif">This message was generated by SCRYPTmail.com on behalf of <b>*|SENDER|*</b>.<br><br>

<p style="font-family:'Calibri',sans-serif">This message was generated by SCRYPTmail.com on behalf of <b>*|SENDER|*</b>.<br><br>

-----------------<br>
scryptmail.com - privacy is your right, not a privilege.
<span class="clear"></span></p>
</body>
</html>