<html>
<head>
</head>

<body>
<p style="font-family:'Calibri',sans-serif">Hello *|RECIPIENT|*,</p>
<p style="font-family:'Calibri',sans-serif">*|SENDER|* sent you a encrypted email using <a href='https://scryptmail.com'>SCRYPTmail</a>.
	private email service. You can read this email by clicking the following link:</p>

<p style="font-family:'Calibri',sans-serif"><a href='*|LINK_TO_MESSAGE|*'>Show email</a></p>
<br><br>*|LINK_TO_MESSAGE|*
<br><br>
<p style="font-family:'Calibri',sans-serif">Original email will be available for the next 14 days. After that it will be deleted. You can also delete it by following link, and selecting delete.</p>

<p style="font-family:'Calibri',sans-serif">This message was generated by SCRYPTmail.com on behalf of <b>*|SENDER|*</b>.
	<br><br>
	-----------------
	<br>
	scryptmail.com - privacy is your right, not a privilege.
	<span class="clear"></span></p>

</body>
</html>